---
classes:
  - r10k
  - r10k::webhook
  - r10k::webhook::config

r10k::remote: 'git@github.com:pscadiz/puppet-stuff.git'
r10k::webhook::use_mcollective: false
r10k::webhook::config::use_mcollective: false
